### ISSUE TITLE
Doesn't work in Async Scripts

### ISSUE THREAD

**Issue by imsus** [dsurgeons/OpenShare#5]
Using data-attributes and initiate with async scripts. [Demo](http://codepen.io/imsus/pen/XjBKWv)

Because no console error logs. It's hard to track.

**Comment by jakeburden** [comment]
I'm so glad you've reported this 👍 

This bug is really interesting. I've found the problem: 

We have been using `document.addEventListener('DOMContentLoaded', callback)` to ensure the data-attributes are on the page before openshare runs.  However, with `<script async ...` openshare is actually being parsed _after_ the DOM loads, which means openshare is missing the DOMContentLoaded event and never runs.

What we ought to do instead (or additionally) is check for [document.readyState](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState#Different_states_of_readiness).  This is what [jQuery(document).ready()](https://github.com/jquery/jquery/blob/master/src/core/ready-no-deferred.js#L86-L96) does. Or, alternatively, use [document.onreadystatechange](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState#readystatechange_as_an_alternative_to_DOMContentLoaded_event).

If you want to take on the initiative to send a pull request I'd be glad to see it through and answer any questions along the way!

Otherwise, I'll try my best to fix this soon.

Thank you @imsus 🎉

**Comment by himanshu81494** [comment]
I would like to work on it.

**Comment by jakeburden** [comment]
Merged the fix from @matteo-hertel and published it to npm

@imsus you should be able use the cdn reference in [this demo](http://codepen.io/jekrb/pen/WGgYjJ) until the cache on cdn.rawgit.com refreshes

thank you so much everyone 😄
