### ISSUE TITLE
Requires Babelify with Browserify

### ISSUE THREAD

**Issue by danhere** [dsurgeons/OpenShare#9]
Installed OpenShare with npm and added `var OpenShare = require('openshare');` to my script.

Upon compilation, it throws an error that it requires babelify but that isn't installed as a dependency. Is Babelify required to use OpenShare?

**Comment by jakeburden** [comment]
Howdy @danhere 👋  Our goal since (1.0.0) was that those who [weren't using babelify could still use openshare by doing `require('openshare/dist/openshare')`](https://github.com/OpenShare/openshare/wiki/1.-Getting-Started#using-npm-but-not-a-transpiler-like-babel).  We should probably make this more clear in the readme.

There is an example of using [babelify with browserify in our package.json](https://github.com/OpenShare/openshare/blob/master/package.json#L6-L21).  We use the npm scripts highlighted there for testing.

However, as mentioned in #3 and #8 we're looking for better ways to publish this module so that babelify isn't really required.  If you're running into issues with `npm` installs you can use this CDN: `<script  src='https://cdn.rawgit.com/OpenShare/openshare/master/dist/openshare.js'></script>` 

If you're not using the CDN and the recent ES2015ify'd version of openshare isn't building due to it's ES2015yness, you can install the pre-ES2015 version by doing `npm i openshare@1.4.4 -S` or `npm i github://OpenShare/openshare#23ee2b80e4af31076e5ff526e51b1d7f5ee503f3 -S`

**Comment by danhere** [comment]
Awesome. I'll give that a shot. Thanks!
